[package]
name = "adaptive_work_stealing"
version = "0.1.0"
authors = ["Maiko Müller"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = {path = "../rayon"}
lazy_static = "*"
